---
jobs:
  - name: null-job
    schedule: "0 0 0 * * *"
    command: "/bin/bash, :"
    prep:
      name: s3-backup
      command: "/bin/bash, count3.sh, creds.access_key, creds.secret_key, creds.bucket, creds.folder, uri.eservice"
